version: "3.9"
services:
  bds-rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
  bds-webclient:
    image: bms-webclient
    depends_on:
      - bds-rabbitmq
    env_file:
      - rabbitmq_configuration.env
    ports:
      - 5000:80
  bds-worker:
    image: bms-worker
    depends_on:
      - bds-rabbitmq
    env_file:
      - rabbitmq_configuration.env
