version: "3.9"
services:
  bms-rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5672:5672
      - 15672:15672
  bms-webclient:
    image: bms-webclient
    depends_on:
      - bms-rabbitmq
    env_file:
      - rabbitmq_configuration.env
    ports:
      - 5000:80
  bms-worker:
    image: bms-worker
    depends_on:
      - bms-rabbitmq
    env_file:
      - rabbitmq_configuration.env
